#!/usr/bin/env bash
# displays Best School 10 times, but shows "Hi" after 9th iteration

COUNTER=1
while [ "$COUNTER" -le 10 ]
do
    echo "Best School"
    if [ "$COUNTER" -eq 9 ]
    then
        echo "Hi"
    fi
    ((COUNTER++))
done

