#!/usr/bin/env bash
# displays different messages depending on COUNTER value

COUNTER=1
while [ $COUNTER -le 10 ]
do
    if [ $COUNTER = 4 ]; then
        echo "bad luck"
    elif [ $COUNTER = 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( COUNTER++ ))
done

