#!/usr/bin/env bash
# Bu skript sonsuz dövrə ilə "To infinity and beyond" yazır və siqnal alanda dayanır

trap "echo 'Terminated'; exit" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 1
done

